<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MailRecipient;

class MailRecipientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            ['nombre' => null, 'email' => 'eamunoz@dpp.cl', 'orden' => 1],
            ['nombre' => null, 'email' => 'hchaperon@dpp.cl', 'orden' => 2],
            ['nombre' => null, 'email' => 'hsilva@dpp.cl', 'orden' => 3],
            ['nombre' => null, 'email' => 'jocelyne.diaz@dpp.cl', 'orden' => 4],
            ['nombre' => null, 'email' => 'jose.zarate@dpp.cl', 'orden' => 5],
            ['nombre' => null, 'email' => 'ldidomenico@dpp.cl', 'orden' => 6],
            ['nombre' => null, 'email' => 'maraya@dpp.cl', 'orden' => 7],
            ['nombre' => null, 'email' => 'maria.troncoso@dpp.cl', 'orden' => 8],
            ['nombre' => null, 'email' => 'mquezada@dpp.cl', 'orden' => 9],
            ['nombre' => null, 'email' => 'pmunizaga@dpp.cl', 'orden' => 10],
            ['nombre' => null, 'email' => 'psanzana@dpp.cl', 'orden' => 11],
            ['nombre' => null, 'email' => 'urgencias.santiago@dpp.cl', 'orden' => 12],
            ['nombre' => null, 'email' => 'vcontreras@dpp.cl', 'orden' => 13],
            ['nombre' => null, 'email' => 'vprovidel@dpp.cl', 'orden' => 14],
            ['nombre' => null, 'email' => 'ac.campora@gmail.com', 'orden' => 15],
            ['nombre' => null, 'email' => 'acacevedom@gmail.com', 'orden' => 16],
            ['nombre' => 'Carolina Herrera Sabando', 'email' => 'acarohs@gmail.com', 'orden' => 17],
            ['nombre' => null, 'email' => 'akarina2916@gmail.com', 'orden' => 18],
            ['nombre' => null, 'email' => 'alecuadragalarce@gmail.com', 'orden' => 19],
            ['nombre' => null, 'email' => 'amelia.munoz.molina@gmail.com', 'orden' => 20],
            ['nombre' => null, 'email' => 'antogmster@gmail.com', 'orden' => 21],
            ['nombre' => null, 'email' => 'carolina.musabeli@gmail.com', 'orden' => 22],
            ['nombre' => null, 'email' => 'catoncio@gmail.com', 'orden' => 23],
            ['nombre' => null, 'email' => 'cflopez.pjud@gmail.com', 'orden' => 24],
            ['nombre' => null, 'email' => 'cg.jeria.montoya@gmail.com', 'orden' => 25],
            ['nombre' => null, 'email' => 'claudia.morgado.m@gmail.com', 'orden' => 26],
            ['nombre' => null, 'email' => 'crisfu79@gmail.com', 'orden' => 27],
            ['nombre' => null, 'email' => 'cristi.62.cabello@gmail.com', 'orden' => 28],
            ['nombre' => 'Cristian Soto Galdames', 'email' => 'csoto.galdames@gmail.com', 'orden' => 29],
            ['nombre' => 'Cristina Valenzuela V.', 'email' => 'cvalenzuelav@gmail.com', 'orden' => 30],
            ['nombre' => null, 'email' => 'diazgcamila@gmail.com', 'orden' => 31],
            ['nombre' => null, 'email' => 'erivena@gmail.com', 'orden' => 32],
            ['nombre' => null, 'email' => 'escandon.c@gmail.com', 'orden' => 33],
            ['nombre' => 'GENI MORALES E.', 'email' => 'espimog@gmail.com', 'orden' => 34],
            ['nombre' => null, 'email' => 'i.espinoza1585@gmail.com', 'orden' => 35],
            ['nombre' => null, 'email' => 'lfwernerm@gmail.com', 'orden' => 36],
            ['nombre' => null, 'email' => 'mariaelisa.tapia@gmail.com', 'orden' => 37],
            ['nombre' => null, 'email' => 'natyruz1311@gmail.com', 'orden' => 38],
            ['nombre' => null, 'email' => 'pabloibaz@gmail.com', 'orden' => 39],
            ['nombre' => null, 'email' => 'paravenab@gmail.com', 'orden' => 40],
            ['nombre' => null, 'email' => 'pbrundl@gmail.com', 'orden' => 41],
            ['nombre' => null, 'email' => 'renebonnemaison@gmail.com', 'orden' => 42],
            ['nombre' => null, 'email' => 'rm.salgado.91@gmail.com', 'orden' => 43],
            ['nombre' => null, 'email' => 'romina.salgadop@gmail.com', 'orden' => 44],
            ['nombre' => 'Maria Elena Troncoso Troncoso', 'email' => 'troncoso.troncosom@gmail.com', 'orden' => 45],
            ['nombre' => null, 'email' => 'coredrak@hotmail.com', 'orden' => 46],
            ['nombre' => null, 'email' => 'edo_fredes@hotmail.com', 'orden' => 47],
            ['nombre' => null, 'email' => 'jcurrutiap@hotmail.com', 'orden' => 48],
            ['nombre' => null, 'email' => 'karlafranciscafaundezmolina@hotmail.com', 'orden' => 49],
            ['nombre' => null, 'email' => 'luiswerner@hotmail.com', 'orden' => 50],
            ['nombre' => null, 'email' => 'mc_garcia_8@hotmail.com', 'orden' => 51],
            ['nombre' => null, 'email' => 'musabeli@hotmail.com', 'orden' => 52],
            ['nombre' => null, 'email' => 'paulisariego@hotmail.com', 'orden' => 53],
            ['nombre' => null, 'email' => 'acadiz@minpublico.cl', 'orden' => 54],
            ['nombre' => null, 'email' => 'apizarroy@minpublico.cl', 'orden' => 55],
            ['nombre' => 'Carolina Ortiz Bennett', 'email' => 'cortizb@minpublico.cl', 'orden' => 56],
            ['nombre' => null, 'email' => 'eguevara@minpublico.cl', 'orden' => 57],
            ['nombre' => 'Francisco Jacir Manterola', 'email' => 'fjacir@minpublico.cl', 'orden' => 58],
            ['nombre' => null, 'email' => 'hbrizuela@minpublico.cl', 'orden' => 59],
            ['nombre' => null, 'email' => 'holea@minpublico.cl', 'orden' => 60],
            ['nombre' => 'Juan Agustín Morales Maldonado', 'email' => 'jamorales@minpublico.cl', 'orden' => 61],
            ['nombre' => null, 'email' => 'jmorales@minpublico.cl', 'orden' => 62],
            ['nombre' => null, 'email' => 'kdecortillas@minpublico.cl', 'orden' => 63],
            ['nombre' => null, 'email' => 'kflorese@minpublico.cl', 'orden' => 64],
            ['nombre' => null, 'email' => 'krepetti@minpublico.cl', 'orden' => 65],
            ['nombre' => null, 'email' => 'lserra@minpublico.cl', 'orden' => 66],
            ['nombre' => null, 'email' => 'mgatica@minpublico.cl', 'orden' => 67],
            ['nombre' => null, 'email' => 'pbenavidesr@minpublico.cl', 'orden' => 68],
            ['nombre' => null, 'email' => 'rbravo@minpublico.cl', 'orden' => 69],
            ['nombre' => null, 'email' => 'sbarrueto@minpublico.cl', 'orden' => 70],
            ['nombre' => null, 'email' => 'sgonzalez@minpublico.cl', 'orden' => 71],
            ['nombre' => null, 'email' => 'smatamala@minpublico.cl', 'orden' => 72],
            ['nombre' => null, 'email' => 'spacheco@minpublico.cl', 'orden' => 73],
            ['nombre' => null, 'email' => 'vconcha@minpublico.cl', 'orden' => 74],
            ['nombre' => null, 'email' => 'vmartinez@minpublico.cl', 'orden' => 75],
            ['nombre' => null, 'email' => 'xaraneda@minpublico.cl', 'orden' => 76],
            ['nombre' => null, 'email' => 'xchong@minpublico.cl', 'orden' => 77],
            ['nombre' => null, 'email' => 'ymontoya@minpublico.cl', 'orden' => 78],
            ['nombre' => null, 'email' => 'aacevedo@pjud.cl', 'orden' => 79],
            ['nombre' => 'Alvaro Astudillo Berrios', 'email' => 'aastudillo@pjud.cl', 'orden' => 80],
            ['nombre' => null, 'email' => 'acgodoy@pjud.cl', 'orden' => 81],
            ['nombre' => null, 'email' => 'acherrera@pjud.cl', 'orden' => 82],
            ['nombre' => 'AMELIA C. MUNOZ MOLINA', 'email' => 'acmunoz@pjud.cl', 'orden' => 83],
            ['nombre' => null, 'email' => 'aparra@pjud.cl', 'orden' => 84],
            ['nombre' => null, 'email' => 'bvalencia@pjud.cl', 'orden' => 85],
            ['nombre' => null, 'email' => 'cafuentealba@pjud.cl', 'orden' => 86],
            ['nombre' => 'Cristina Del Cabello Munoz', 'email' => 'ccabello@pjud.cl', 'orden' => 87],
            ['nombre' => 'CARLOS DONOSO BRAVO', 'email' => 'cdonosob@pjud.cl', 'orden' => 88],
            ['nombre' => null, 'email' => 'cecastillo@pjud.cl', 'orden' => 89],
            ['nombre' => 'Carolina Paz Escandon Cox', 'email' => 'cescandon@pjud.cl', 'orden' => 90],
            ['nombre' => null, 'email' => 'cmorgado@pjud.cl', 'orden' => 91],
            ['nombre' => 'CAROLINA MUSABELI VALDES', 'email' => 'cmusabeli@pjud.cl', 'orden' => 92],
            ['nombre' => 'CRISTIAN SOTO GALDAMES', 'email' => 'csoto@pjud.cl', 'orden' => 93],
            ['nombre' => null, 'email' => 'ctoncio@pjud.cl', 'orden' => 94],
            ['nombre' => 'CRISTINA VALENZUELA VILCHES', 'email' => 'cvalenzuelav@pjud.cl', 'orden' => 95],
            ['nombre' => null, 'email' => 'cvdiaz@pjud.cl', 'orden' => 96],
            ['nombre' => null, 'email' => 'cvillegas@pjud.cl', 'orden' => 97],
            ['nombre' => null, 'email' => 'earavena@pjud.cl', 'orden' => 98],
            ['nombre' => 'Eduardo Mauricio Fredes Tapia', 'email' => 'efredes@pjud.cl', 'orden' => 99],
            ['nombre' => 'EMILIO GONZALEZ FAUNES', 'email' => 'egonzalezf@pjud.cl', 'orden' => 100],
            ['nombre' => null, 'email' => 'emtorres@pjud.cl', 'orden' => 101],
            ['nombre' => null, 'email' => 'enmartinez@pjud.cl', 'orden' => 102],
            ['nombre' => 'GENI MORALES ESPINOZA', 'email' => 'gmoralese@pjud.cl', 'orden' => 103],
            ['nombre' => null, 'email' => 'gvalenzuelau@pjud.cl', 'orden' => 104],
            ['nombre' => null, 'email' => 'hgarrido@pjud.cl', 'orden' => 105],
            ['nombre' => null, 'email' => 'ipespinoza@pjud.cl', 'orden' => 106],
            ['nombre' => 'JUAN CARLOS URRUTIA PADILLA', 'email' => 'jcurrutia@pjud.cl', 'orden' => 107],
            ['nombre' => null, 'email' => 'jisaac@pjud.cl', 'orden' => 108],
            ['nombre' => null, 'email' => 'jmoraga@pjud.cl', 'orden' => 109],
            ['nombre' => null, 'email' => 'jmurguia@pjud.cl', 'orden' => 110],
            ['nombre' => null, 'email' => 'jtroncosor@pjud.cl', 'orden' => 111],
            ['nombre' => 'Karina Paz Aguilera Poveda', 'email' => 'kaguilera@pjud.cl', 'orden' => 112],
            ['nombre' => null, 'email' => 'kfaundez@pjud.cl', 'orden' => 113],
            ['nombre' => null, 'email' => 'kgonzalezo@pjud.cl', 'orden' => 114],
            ['nombre' => null, 'email' => 'lrmorales@pjud.cl', 'orden' => 115],
            ['nombre' => null, 'email' => 'mcsaez@pjud.cl', 'orden' => 116],
            ['nombre' => null, 'email' => 'mcuadra@pjud.cl', 'orden' => 117],
            ['nombre' => 'MARCELO DUARTE PRADO', 'email' => 'meduarte@pjud.cl', 'orden' => 118],
            ['nombre' => null, 'email' => 'mfernandezu@pjud.cl', 'orden' => 119],
            ['nombre' => 'Maria Jose Garcia Ramirez', 'email' => 'mjgarcia@pjud.cl', 'orden' => 120],
            ['nombre' => 'MARIA LORETO SANDOVAL MARTINEZ', 'email' => 'mlsandoval@pjud.cl', 'orden' => 121],
            ['nombre' => 'Macarena Munro', 'email' => 'mmunro@pjud.cl', 'orden' => 122],
            ['nombre' => null, 'email' => 'msantos@pjud.cl', 'orden' => 123],
            ['nombre' => 'MARIA ELISA TAPIA ARAYA', 'email' => 'mtapia@pjud.cl', 'orden' => 124],
            ['nombre' => null, 'email' => 'nruz@pjud.cl', 'orden' => 125],
            ['nombre' => null, 'email' => 'pbrundl@pjud.cl', 'orden' => 126],
            ['nombre' => null, 'email' => 'pcaravena@pjud.cl', 'orden' => 127],
            ['nombre' => null, 'email' => 'pibaceta@pjud.cl', 'orden' => 128],
            ['nombre' => null, 'email' => 'psancristobal@pjud.cl', 'orden' => 129],
            ['nombre' => null, 'email' => 'psariego@pjud.cl', 'orden' => 130],
            ['nombre' => 'PEDRO HUMBERTO SUAREZ NIETO', 'email' => 'psuarez@pjud.cl', 'orden' => 131],
            ['nombre' => null, 'email' => 'rbonnemaison@pjud.cl', 'orden' => 132],
            ['nombre' => 'Sylvia Bustamante Barraza', 'email' => 'sbustamante@pjud.cl', 'orden' => 133],
            ['nombre' => 'Acta1_tosantiago4', 'email' => 'top1247s01@pjud.cl', 'orden' => 134],
            ['nombre' => 'Sala De Audiencias 8. 3', 'email' => 'top1247s02@pjud.cl', 'orden' => 135],
            ['nombre' => 'Sala De Audiencias 8. 1', 'email' => 'top1247s03@pjud.cl', 'orden' => 136],
            ['nombre' => 'Correo Sala 902', 'email' => 'top1247s04@pjud.cl', 'orden' => 137],
            ['nombre' => null, 'email' => 'top1247s05@pjud.cl', 'orden' => 138],
            ['nombre' => 'Correo Sala 6', 'email' => 'top1247s06@pjud.cl', 'orden' => 139],
            ['nombre' => null, 'email' => 'tzurita@pjud.cl', 'orden' => 140],
            ['nombre' => null, 'email' => 'vojeda@pjud.cl', 'orden' => 141]
        ];

        foreach ($rows as $i => $r) {
            MailRecipient::updateOrCreate(
                ['email' => $r['email']],
                [
                    'nombre' => $r['nombre'],
                    'activo' => true,
                    'orden'  => $r['orden'],
                ]
            );
        }
    }
}
